export default [
    {
        id: 1,
        name: 'Matthew',
        job: 'Early Supporter',
        img: '/assets/img/testimonial/testimonial-1.webp',
        description: "We can’t wait for the launch! The team’s passion and dedication to crafting unique, high-quality drinks is evident in every step. It’s clear that this is going to be something special.",
    },
    {
        id: 2,
        name: 'Laara',
        job: 'Environmental Advocate',
        img: '/assets/img/testimonial/testimonial-2.webp',
        description: "Their commitment to sustainability and using eco-friendly processes is inspiring. This is exactly the kind of company we need more of in the market.",
        },
    {
        id: 3,
        name: 'Nikolai',
        job: 'Food & Beverage Enthusiast',
        img: '/assets/img/testimonial/testimonial-3.webp',
        description: "Based on the sneak peeks and concept teasers, I’m excited to see how they push the boundaries of flavor and quality. Can’t wait to try these drinks!",
    },
      {
        id: 4,
        name: 'Jhon Mikias',
        job: 'Collaborator',
        img: '/assets/img/testimonial/testimonial-4.webp',
        description: "Partnering with this team has been a pleasure. Their focus on excellence and innovation promises an exciting addition to the beverage industry.",
      },
      {
        id: 5,
        name: 'Sakura',
        job: 'Industry Insider',
        img: '/assets/img/testimonial/testimonial-5.webp',
        description: "Even before their products are out, you can tell they’re dedicated to using only the best ingredients and processes. That level of commitment gives me confidence in what’s to come.",
      },
      {
        id: 6,
        name: 'Luca',
        job: 'Potential Customer',
        img: '/assets/img/testimonial/testimonial-6.webp',
        description: "The descriptions and early concept ideas sound amazing! I’m eagerly awaiting that first sip – I’m sure it’ll be worth the wait.",
      },
      {
        id: 7,
        name: 'Thiago',
        job: 'Health & Wellness Blogger',
        img: '/assets/img/testimonial/testimonial-7.webp',
        description: "The brand’s dedication to creating refreshing, health-conscious drinks is something I admire. I’m excited to see how they’ll stand out in the market.",
      },
  ];