export default [
    {
        id: 1,
        name: 'E. Donaldson:',
        job: 'Student',
        img: '/assets/img/testimonial/testimonial-1.webp',
        description: "From zero knowledge to becoming a professional Business Analyst in the Digital Transformation space, Tritek guided me every step of the way!",
    },
    {
        id: 2,
        name: 'Jayson',
        job: 'Student',
        img: '/assets/img/testimonial/testimonial-2.webp',
        description: "Within 2 hours of my final interview, I received a job offer as a Project Manager at the top salary range. Tritek made it possible!",
        },
    {
        id: 3,
        name: 'Sarah J.',
        job: 'Student',
        img: '/assets/img/testimonial/testimonial-3.webp',
        description: "The hands-on projects prepared me so well that I landed a job in Cybersecurity with confidence I never had before",
    },
      {
        id: 4,
        name: 'James K.',
        job: 'Student',
        img: '/assets/img/testimonial/testimonial-4.webp',
        description: "Their mentorship program isn’t just support—it’s life-changing. I transitioned from a low-paying job to a fulfilling career in Digital Marketing.",
      },
      {
        id: 5,
        name: 'Angela T.',
        job: 'Student',
        img: '/assets/img/testimonial/testimonial-5.webp',
        description: "Tritek didn’t just teach me; they transformed me. I now have a job I love and the skills to excel in it.",
      },
      {
        id: 6,
        name: 'Michael P.',
        job: 'Student',
        img: '/assets/img/testimonial/testimonial-6.webp',
        description: "Tritek’s flexible learning options allowed me to juggle shift work and studies, and their mentorship helped me secure a job as a Cloud Engineer.",
      },
      {
        id: 7,
        name: 'Thiago',
        job: 'Student',
        img: '/assets/img/testimonial/testimonial-7.webp',
        description: "Tritek’s training gave me the confidence and skills to secure a Business Development Manager role, improving my career and income.",
      },
  ];