export default [
    {
        id: 1,
        name: 'Victor:',
        job: 'Student',
        img: '/assets/img/testimonial/victor.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/victor.mp4',
        description: "It was a very great learning experience and I just want to be grateful to all the staff of Tritek for the learning experience and assistance.",
    },
    {
        id: 2,
        name: 'Olalapo Owoniyi',
        job: 'Student',
        img: '/assets/img/testimonial/ololapo.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/olalapo-owoniyi.mp4',
        description: "I will sum up my overall experience so far on this course as enlightning. Learned so much on BA deliverables on different section of the project life cycle.",
        },
    {
        id: 3,
        name: 'Regha',
        job: 'Student',
        img: '/assets/img/testimonial/regha.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/Richy-Regha.mp4',
        description: "The experience so far has been very valuable. I now have a deeper understanding of what it really means to be an analyst and look forward to completing the life project with my team.",
    },
      {
        id: 4,
        name: 'Marilyn',
        job: 'Student',
        img: '/assets/img/testimonial/marilyn.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/marilyn.mp4',
        description: "Tritek is very accomodating. They saw my situation and gave me an offer that showed they cared and I'm grateful for the understanding.",
      },
      {
        id: 5,
        name: 'Raviat',
        job: 'Student',
        img: '/assets/img/testimonial/raviat.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/raviat.mp4',
        description: "At first I was skeptical since I wasn't sure of what path to take but with assistance from Tritek and my team members, the projects were a blazing success.",
      },
      {
        id: 6,
        name: 'Abimbola.',
        job: 'Student',
        img: '/assets/img/testimonial/abimbola.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/abimbola.mp4',
        description: "Joining Tritek is one of the best decisions I've ever made. After the rigorous training, we had to work on a real life project which gave me opportunities to work with diverse teams.",
      },
      {
        id: 7,
        name: 'Damola',
        job: 'Student',
        img: '/assets/img/testimonial/damola.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/damola.mp4',
        description: "With no knowledge about Project Management or Business Analysis, Tritek was able to take me from zero knowledge to being employable with work experience in record time",
      },
      {
        id: 8,
        name: 'Matthew',
        job: 'Student',
        img: '/assets/img/testimonial/matthew.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/matthew.mp4',
        description: "I want to say that the training was awesome. As a teacher myself, I appreciated just how much knowledge the lecturers had and their willingness to impart.",
      },
      {
        id: 9,
        name: 'Amuchi Noman',
        job: 'Student',
        img: '/assets/img/testimonial/amuchi.webp',
        video: 'https://culturefoodsmarket.com/wp-content/uploads/2024/12/amuchi.mp4',
        description: "It was one of the best investments I've made with my money. Very interesting, learned new persons and increased my network and experience.",
      },
  ];